### ISSUE TITLE
[Instance] New instance request

### ISSUE THREAD

**Issue by lnxredir** [whereismybugfix/wikiless#1]
URL: https:/wkl.frail.duckdns.org/
Onion: N/A
Country: Brazil
Cloudflare: no

If you need any additional information just let me know. Also sorry for not opening a pull request, I`m not familiar with github and couldn't make one, and lastly thanks for keeping such an awesome project alive!

**Comment by whereismybugfix** [comment]
Hey, @lnxredir. I'm adding it to the list. You are very welcome!
