### ISSUE TITLE
Change in instance domain.

### ISSUE THREAD

**Issue by lnxredir** [whereismybugfix/wikiless#4]
Hey, sorry for opening an issue for something like this, I recently bought a domain and would like to change my instance URL, from **wkl.frail.duckdns.org** to **wkl.frail.com.br**, please. Thank you for keeping this project alive and going mate, if you have a way of making a donation, I'd happily its not much but I know every bit helps.

**Comment by whereismybugfix** [comment]
Hello @lnxredir, sorry for the late answer. I was a little bit away from any opensource stuff for a while. From now on I'll be more responsive on incoming issues. 

Thank you for the suggestion! Once I come up with more big and popular opensource projects, I'll create a link for donations here on GitHub. But for now, I'm happy to help for free. That's what opensource is for!

I'm gonna change the domain right now. You are welcome!
